project "Assimp"
	kind "StaticLib"  
	language "C++"
	cppdialect "c++17"
	staticruntime "on"

	-- Isard is here to fix, I've been notified --

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin/int/" .. outputdir .. "/%{prj.name}")
	
	includedirs
	{
		"Build/include",
		"Build/",
		"include/",
		"code",
		"./",
		"contrib/zlib",
		"Build/contrib/zlib",
		"contrib/rapidjson/include",
		"contrib",
		"contrib/unzip",
		"contrib/irrXML",
		"contrib/openddlparser/include",
	}

	files
	{
		"code/CApi/CInterfaceIOWrapper.cpp",
		"code/Common/**.cpp",
		"code/Common/**.h",
		"code/CApi/AssimpCExport.cpp",
		"code/MDL/HalfLife/**.cpp",
		"code/MDL/HalfLife/**.h",
		"code/PostProcessing/**.cpp",
		"code/PostProcessing/**.h",
		"code/PostProcessing/GenBoundingBoxesProcess.cpp",
		"code/Material/MaterialSystem.cpp",
		"code/Importer/STEPParser/STEPFileReader.cpp",
		"code/Importer/STEPParser/STEPFileEncoding.cpp",
		"code/AMF/AMFImporter.cpp",
		"code/AMF/AMFImporter_Geometry.cpp",
		"code/AMF/AMFImporter_Material.cpp",
		"code/AMF/AMFImporter_Postprocess.cpp",
		"code/3DS/3DSConverter.cpp",
		"code/3DS/3DSLoader.cpp",
		"code/AC/ACLoader.cpp",
		"code/ASE/ASELoader.cpp",
		"code/ASE/ASEParser.cpp",
		"code/Assbin/AssbinLoader.cpp",
		"code/B3D/B3DImporter.cpp",
		"code/BVH/BVHLoader.cpp",
		"code/Collada/ColladaLoader.cpp",
		"code/Collada/ColladaParser.cpp",
		"code/DXF/DXFLoader.cpp",
		"code/CSM/CSMLoader.cpp",
		"code/HMP/HMPLoader.cpp",
		"code/Irr/IRRMeshLoader.cpp",
		"code/Irr/IRRShared.cpp",
		"code/Irr/IRRLoader.cpp",
		"code/LWO/LWOAnimation.cpp",
		"code/LWO/LWOBLoader.cpp",
		"code/LWO/LWOLoader.cpp",
		"code/LWO/LWOMaterial.cpp",
		"code/LWS/LWSLoader.cpp",
		"code/MD2/MD2Loader.cpp",
		"code/MD3/MD3Loader.cpp",
		"code/MD5/MD5Loader.cpp",
		"code/MD5/MD5Parser.cpp",
		"code/MDC/MDCLoader.cpp",
		"code/MDL/MDLLoader.cpp",
		"code/M3D/**.cpp",
		"code/M3D/**.h",
		"code/MDL/MDLMaterialLoader.cpp",
		"code/NFF/NFFLoader.cpp",
		"code/NDO/NDOLoader.cpp",
		"code/OFF/OFFLoader.cpp",
		"code/Obj/ObjFileImporter.cpp",
		"code/Obj/ObjFileMtlImporter.cpp",
		"code/Obj/ObjFileParser.cpp",
		"code/Ogre/OgreImporter.cpp",
		"code/Ogre/OgreStructs.cpp",
		"code/Ogre/OgreBinarySerializer.cpp",
		"code/Ogre/OgreXmlSerializer.cpp",
		"code/Ogre/OgreMaterial.cpp",
		"code/OpenGEX/OpenGEXImporter.cpp",
		"code/Ply/PlyLoader.cpp",
		"code/Ply/PlyParser.cpp",
		"code/MS3D/MS3DLoader.cpp",
		"code/COB/COBLoader.cpp",
		"code/Blender/BlenderLoader.cpp",
		"code/Blender/BlenderDNA.cpp",
		"code/Blender/BlenderScene.cpp",
		"code/Blender/BlenderModifier.cpp",
		"code/Blender/BlenderBMesh.cpp",
		"code/Blender/BlenderTessellator.cpp",
		"code/Blender/BlenderCustomData.cpp",
		"code/Importer/IFC/IFCLoader.cpp",
		"code/Importer/IFC/IFCReaderGen1_2x3.cpp",
		"code/Importer/IFC/IFCReaderGen2_2x3.cpp",
		"code/Importer/IFC/IFCUtil.cpp",
		"code/Importer/IFC/IFCGeometry.cpp",
		"code/Importer/IFC/IFCMaterial.cpp",
		"code/Importer/IFC/IFCProfile.cpp",
		"code/Importer/IFC/IFCCurve.cpp",
		"code/Importer/IFC/IFCBoolean.cpp",
		"code/Importer/IFC/IFCOpenings.cpp",
		"code/XGL/XGLLoader.cpp",
		"code/FBX/FBXImporter.cpp",
		"code/FBX/FBXParser.cpp",
		"code/FBX/FBXTokenizer.cpp",
		"code/FBX/FBXConverter.cpp",
		"code/FBX/FBXUtil.cpp",
		"code/FBX/FBXDocument.cpp",
		"code/FBX/FBXProperties.cpp",
		"code/FBX/FBXMeshGeometry.cpp",
		"code/FBX/FBXMaterial.cpp",
		"code/FBX/FBXModel.cpp",
		"code/FBX/FBXAnimation.cpp",
		"code/FBX/FBXNodeAttribute.cpp",
		"code/FBX/FBXDeformer.cpp",
		"code/FBX/FBXBinaryTokenizer.cpp",
		"code/FBX/FBXDocumentUtil.cpp",
		"code/Q3D/Q3DLoader.cpp",
		"code/Q3BSP/Q3BSPFileParser.cpp",
		"code/Q3BSP/Q3BSPFileImporter.cpp",
		"code/Raw/RawLoader.cpp",
		"code/SIB/SIBImporter.cpp",
		"code/SMD/SMDLoader.cpp",
		"code/STL/STLLoader.cpp",
		"code/Terragen/TerragenLoader.cpp",
		"code/Unreal/UnrealLoader.cpp",
		"code/X/XFileImporter.cpp",
		"code/X/XFileParser.cpp",
		"code/X3D/X3DImporter.cpp",
		"code/X3D/X3DImporter_Geometry2D.cpp",
		"code/X3D/X3DImporter_Geometry3D.cpp",
		"code/X3D/X3DImporter_Group.cpp",
		"code/X3D/X3DImporter_Light.cpp",
		"code/X3D/X3DImporter_Metadata.cpp",
		"code/X3D/X3DImporter_Networking.cpp",
		"code/X3D/X3DImporter_Postprocess.cpp",
		"code/X3D/X3DImporter_Rendering.cpp",
		"code/X3D/X3DImporter_Shape.cpp",
		"code/X3D/X3DImporter_Texturing.cpp",
		"code/X3D/FIReader.cpp",
		"code/X3D/X3DVocabulary.cpp",
		"code/glTF/**.cpp",
		"code/glTF/**.h",
		"code/glTF2/glTF2Importer.cpp",
		"code/3MF/D3MFImporter.cpp",
		"code/3MF/D3MFOpcPackage.cpp",
		"code/MMD/MMDImporter.cpp",
		"code/MMD/MMDPmxParser.cpp",
		"code/Importer/StepFile/StepFileImporter.cpp",
		"code/Importer/StepFile/StepFileGen1.cpp",
		"code/Importer/StepFile/StepFileGen2.cpp",
		"code/Importer/StepFile/StepFileGen3.cpp",
		"code/3DS/3DSExporter.cpp",
		"code/Assbin/AssbinExporter.cpp",
		"code/Assxml/AssxmlExporter.cpp",
		"code/Collada/**.cpp",
		"code/Collada/**.h",
		"code/Obj/ObjExporter.cpp",
		"code/OpenGEX/OpenGEXExporter.cpp",
		"code/Ply/PlyExporter.cpp",
		"code/FBX/FBXExporter.cpp",
		"code/FBX/FBXExportNode.cpp",
		"code/FBX/FBXExportProperty.cpp",
		"code/STL/STLExporter.cpp",
		"code/X/XFileExporter.cpp",
		"code/X3D/X3DExporter.cpp",
		"code/glTF/glTFExporter.cpp",
		"code/glTF2/glTF2Exporter.cpp",
		"code/3MF/D3MFExporter.cpp",
		"code/Assjson/cencode.c",
		"code/Assjson/json_exporter.cpp",
		"code/Assjson/mesh_splitter.cpp",
		"code/Step/StepExporter.cpp",
		"contrib/unzip/ioapi.c",
		"contrib/unzip/unzip.c",
		"contrib/poly2tri/poly2tri/common/shapes.cc",
		"contrib/poly2tri/poly2tri/sweep/advancing_front.cc",
		"contrib/poly2tri/poly2tri/sweep/cdt.cc",
		"contrib/poly2tri/poly2tri/sweep/sweep.cc",
		"contrib/poly2tri/poly2tri/sweep/sweep_context.cc",
		"contrib/clipper/clipper.cpp",
		"contrib/openddlparser/code/OpenDDLParser.cpp",
		"contrib/openddlparser/code/DDLNode.cpp",
		"contrib/openddlparser/code/OpenDDLCommon.cpp",
		"contrib/openddlparser/code/OpenDDLExport.cpp",
		"contrib/openddlparser/code/Value.cpp",
		"contrib/openddlparser/code/OpenDDLStream.cpp",
		"contrib/irrXML/irrXML.cpp",
		"code/C4D/C4DImporter.cpp",
		"contrib/zip/src/zip.c",
		"contrib/zlib/adler32.c",
		"contrib/zlib/compress.c",
		"contrib/zlib/crc32.c",
		"contrib/zlib/deflate.c",
		"contrib/zlib/gzclose.c",
		"contrib/zlib/gzlib.c",
		"contrib/zlib/gzread.c",
		"contrib/zlib/gzwrite.c",
		"contrib/zlib/inflate.c",
		"contrib/zlib/infback.c",
		"contrib/zlib/inftrees.c",
		"contrib/zlib/inffast.c",
		"contrib/zlib/trees.c",
		"contrib/zlib/uncompr.c",
		"contrib/zlib/zutil.c",
		"contrib/zlib/zlib.h",
        "build/contrib/zlib/zconf.h",
	}

	filter "system:windows"
		systemversion "latest"
		staticruntime "On"

		defines
		{
			"_CRT_SECURE_NO_WARNINGS",
			"ASSIMP_BUILD_NO_C4D_IMPORTER",
			"ASSIMP_BUILD_NO_OpenGEX_IMPORTER",
			"ASSIMP_BUILD_NO_OpenGEX_EXPORTER",
			"ASSIMP_BUILD_NO_OWN_ZLIB",

            "ASSIMP_BUILD_NO_X_IMPORTER",
            "ASSIMP_BUILD_NO_3DS_IMPORTER",
            "ASSIMP_BUILD_NO_MD3_IMPORTER",
            "ASSIMP_BUILD_NO_MDL_IMPORTER",
            "ASSIMP_BUILD_NO_MD2_IMPORTER",
            -- "ASSIMP_BUILD_NO_PLY_IMPORTER",
            "ASSIMP_BUILD_NO_ASE_IMPORTER",
            -- "ASSIMP_BUILD_NO_OBJ_IMPORTER",
            "ASSIMP_BUILD_NO_AMF_IMPORTER",
            "ASSIMP_BUILD_NO_HMP_IMPORTER",
            "ASSIMP_BUILD_NO_SMD_IMPORTER",
            "ASSIMP_BUILD_NO_MDC_IMPORTER",
            "ASSIMP_BUILD_NO_MD5_IMPORTER",
            "ASSIMP_BUILD_NO_STL_IMPORTER",
            "ASSIMP_BUILD_NO_LWO_IMPORTER",
            "ASSIMP_BUILD_NO_DXF_IMPORTER",
            "ASSIMP_BUILD_NO_NFF_IMPORTER",
            "ASSIMP_BUILD_NO_RAW_IMPORTER",
            "ASSIMP_BUILD_NO_OFF_IMPORTER",
            "ASSIMP_BUILD_NO_AC_IMPORTER",
            "ASSIMP_BUILD_NO_BVH_IMPORTER",
            "ASSIMP_BUILD_NO_IRRMESH_IMPORTER",
            "ASSIMP_BUILD_NO_IRR_IMPORTER",
            "ASSIMP_BUILD_NO_Q3D_IMPORTER",
            "ASSIMP_BUILD_NO_B3D_IMPORTER",
            -- "ASSIMP_BUILD_NO_COLLADA_IMPORTER",
            "ASSIMP_BUILD_NO_TERRAGEN_IMPORTER",
            "ASSIMP_BUILD_NO_CSM_IMPORTER",
            "ASSIMP_BUILD_NO_3D_IMPORTER",
            "ASSIMP_BUILD_NO_LWS_IMPORTER",
            "ASSIMP_BUILD_NO_OGRE_IMPORTER",
            "ASSIMP_BUILD_NO_OPENGEX_IMPORTER",
            "ASSIMP_BUILD_NO_MS3D_IMPORTER",
            "ASSIMP_BUILD_NO_COB_IMPORTER",
            "ASSIMP_BUILD_NO_BLEND_IMPORTER",
            "ASSIMP_BUILD_NO_Q3BSP_IMPORTER",
            "ASSIMP_BUILD_NO_NDO_IMPORTER",
            "ASSIMP_BUILD_NO_IFC_IMPORTER",
            "ASSIMP_BUILD_NO_XGL_IMPORTER",
            -- "ASSIMP_BUILD_NO_FBX_IMPORTER",
            "ASSIMP_BUILD_NO_ASSBIN_IMPORTER",
            -- "ASSIMP_BUILD_NO_GLTF_IMPORTER",
            "ASSIMP_BUILD_NO_C4D_IMPORTER",
            "ASSIMP_BUILD_NO_3MF_IMPORTER",
            "ASSIMP_BUILD_NO_X3D_IMPORTER",
            "ASSIMP_BUILD_NO_MMD_IMPORTER",
            
            "ASSIMP_BUILD_NO_STEP_EXPORTER",
            "ASSIMP_BUILD_NO_SIB_IMPORTER",

            -- "ASSIMP_BUILD_NO_MAKELEFTHANDED_PROCESS",
            -- "ASSIMP_BUILD_NO_FLIPUVS_PROCESS",
            -- "ASSIMP_BUILD_NO_FLIPWINDINGORDER_PROCESS",
            -- "ASSIMP_BUILD_NO_CALCTANGENTS_PROCESS",
            "ASSIMP_BUILD_NO_JOINVERTICES_PROCESS",
            -- "ASSIMP_BUILD_NO_TRIANGULATE_PROCESS",
            "ASSIMP_BUILD_NO_GENFACENORMALS_PROCESS",
            -- "ASSIMP_BUILD_NO_GENVERTEXNORMALS_PROCESS",
            "ASSIMP_BUILD_NO_REMOVEVC_PROCESS",
            "ASSIMP_BUILD_NO_SPLITLARGEMESHES_PROCESS",
            "ASSIMP_BUILD_NO_PRETRANSFORMVERTICES_PROCESS",
            "ASSIMP_BUILD_NO_LIMITBONEWEIGHTS_PROCESS",
            -- "ASSIMP_BUILD_NO_VALIDATEDS_PROCESS",
            "ASSIMP_BUILD_NO_IMPROVECACHELOCALITY_PROCESS",
            "ASSIMP_BUILD_NO_FIXINFACINGNORMALS_PROCESS",
            "ASSIMP_BUILD_NO_REMOVE_REDUNDANTMATERIALS_PROCESS",
            "ASSIMP_BUILD_NO_FINDINVALIDDATA_PROCESS",
            "ASSIMP_BUILD_NO_FINDDEGENERATES_PROCESS",
            "ASSIMP_BUILD_NO_SORTBYPTYPE_PROCESS",
            "ASSIMP_BUILD_NO_GENUVCOORDS_PROCESS",
            "ASSIMP_BUILD_NO_TRANSFORMTEXCOORDS_PROCESS",
            "ASSIMP_BUILD_NO_FINDINSTANCES_PROCESS",
            "ASSIMP_BUILD_NO_OPTIMIZEMESHES_PROCESS",
            "ASSIMP_BUILD_NO_OPTIMIZEGRAPH_PROCESS",
            "ASSIMP_BUILD_NO_SPLITBYBONECOUNT_PROCESS",
            "ASSIMP_BUILD_NO_DEBONE_PROCESS",
            "ASSIMP_BUILD_NO_EMBEDTEXTURES_PROCESS",
            "ASSIMP_BUILD_NO_GLOBALSCALE_PROCESS",
            "OPENDDL_STATIC_LIBARY",
            "UNICODE",
            "_UNICODE"
		}

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"
		buildoptions { "/bigobj" }

	filter "configurations:Release"
		runtime "Release"
		optimize "on"

	filter "configurations:Dist"
		runtime "Release"
		optimize "on"
